### ISSUE TITLE
Multithreaded Java Bindings test

### ISSUE THREAD

**Issue by ianamason** [SRI-CSL/yices2_java_bindings#4]
I added a test based on your simplified one Daniel @baierd. You are welcome to beef this one up to be closer to
what your one does.  I don't get any unreliablilty.

To run the thread test alone:

```
ant threads
```

**Comment by ianamason** [comment]
Can I close this?

**Comment by baierd** [comment]
Most likely yes, since it worked fine in your implementation.
I didn't check back since 2020 in our code as it is a minor issue for us.
But thank you for your work!
